apiVersion: 1

policies:
  - orgId: 1
    receiver: Email
    group_by: ['grafana_folder','alertname']
    object_matchers:
      - ['type', '=', 'license']
    group_wait: 1m
    group_interval: 5m
    repeat_interval: 1h
